<?php
/**
 * @copyright 2017 City of Bloomington, Indiana
 * @license https://www.gnu.org/licenses/old-licenses/gpl-2.0 GNU/GPL2, see LICENSE
 *
 * This file is part of the COB Interactive Maps drupal module.
 *
 * The Maps module is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * The Maps module is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Maps module.  If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0/>.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @implements hook_help()
 */
function interactivemap_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.interactivemap':
            return "<h2>Interactive Maps Help</h2>";
        break;
    }
}

/**
 * @implements hook_theme()
 * @see https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_theme/8.2.x
 */
function interactivemap_theme($existing, $type, $theme, $path)
{
    return [
        'interactivemap_maps' => [
            'template'  => 'interactivemap_maps',
            'variables' => [
                'maps' => [],
            ]
        ]
    ];
}
